2024-12-15 11:59:47,359 - WARNING - Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/Users/borispopko/Documents/Dev/Urban/tests_12_4.py", line 22, in test_run
    test = Runner(442)
           ^^^^^^^^^^^
  File "/Users/borispopko/Documents/Dev/Urban/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-15 11:59:47,359 - WARNING - Неверная скорость для Runner
Traceback (most recent call last):
  File "/Users/borispopko/Documents/Dev/Urban/tests_12_4.py", line 11, in test_walk
    test = Runner('name', speed = -10 )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/borispopko/Documents/Dev/Urban/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
